name: BedwarsRelCloudNetAddon
author: Fridious
description: A simple CloudNetAddon to change the state of server to ingame, if the bedwars game starts
version: 1.0
main: de.fridious.bedwarsrel.cloudnet.addon.BedwarsRelCloudNetAddon
softdepend: [CloudNetAPI,BedwarsRel]
commands:
  bedwarsrelcloudnetaddon:
    usage: /bedwarsrelcloudnetaddon
    description: Advertisment for the author Fridious